### ISSUE TITLE
Using forms.brace.io for static contact form

### ISSUE THREAD

**Issue by taraahmed** [BlackrockDigital/startbootstrap-clean-blog-jekyll#10]
Hello,

I was trying to use forms.brace.io to get the contact form to work straight out of Github pages. It works.

The problem I am having is the messages are being relayed to my inbox, but the 'success' message after someone hits submit isn't actually a success message, It just displays the error/failure message which is written on numerous accounts in the JS validations.

Could someone please help me with why that is happening? If the message is successfully being sent, then why is the failure message coming up?

Thanks
Tara

**Comment by jsheng08** [comment]
Hello, I not sure if you still need this.
I used formspree instead the one you used.
You will need to modify clean-blog.js
```javascript
$.ajax({
                url: "././mail/contact_me.php",
                type: "POST",
                data: {
                    name: name,
                    phone: phone,
                    email: email,
                    message: message
                },
                cache: false,
                success: function() {
```
to something that looks like this
```javascript
$.ajax({
                url: "//formspree.io/mail@jishengtan.me",
                type: "POST",
                data: {
                    name: name,
                    phone: phone,
                    email: email,
                    message: message
                },
                dataType: "json",
                cache: false,
                success: function() {
```
Things I did 
*Changing the url to static email provider
*Add dataType, json.
This quick fix will help people that host their static site on github since it doesn't run php code at all.

**Comment by davidtmiller** [comment]
Thanks for this contribution! I am going to review it and see if I can get this working. I like this format better, especially since GitHub pages isn't going to be running the form well. Thanks!

**Comment by davidtmiller** [comment]
Added Formspree integration in place of the PHP file.
