### ISSUE TITLE
Modify the background-cover size

### ISSUE THREAD

**Issue by yyanruo** [BlackrockDigital/startbootstrap-clean-blog-jekyll#105]
Hi, I want to modify the background-cover size because the my images' size doesn't fit the cover. so i check the code to find where i can modify this.

- page.html: find the class of "intro-header" 
- mixins.less: find the "background-cover"

but i still can't find  the way to modify the cover, could you help to solve this problem? 

@Suhas SG

**Comment by davidtmiller** [comment]
You would need to overwrite the header options in your own CSS on top of the Clean Blog CSS since it's imported through npm.
