### ISSUE TITLE
Use highlight.js in startbootstrap-clean-blog-jekyll

### ISSUE THREAD

**Issue by Huang-Libo** [BlackrockDigital/startbootstrap-clean-blog-jekyll#109]
Can I use highlight.js in startbootstrap-clean-blog-jekyll?

**Comment by i-a-n** [comment]
I use a customized highlight.js theme on my Clean Blog install. and I use a custom variable to decide whether to load the CSS/JS or not. an example post with it is [here](https://blog.union.io/code/2016/07/22/managing-svgs-in-react/), and you can see my commit to add the whole thing [on my repo](https://github.com/i-a-n/unionjkl/commit/3d7c8d2d726ccaf8745da25fc3071db55c47a125).

**Comment by Huang-Libo** [comment]
@i-a-n  
Hi, I use your method step by step and I successfully install the `union-syntaxhighlighter-theme`, however I want to use `tomorrow-night-bright.css` theme and my own `highlight.pack.js`, I try to change `union-syntaxhighlighter-slim.min.js` with my own `highlight.pack.js`, and change `union-syntaxhighlighter.css` with `tomorrow-night-bright.css`, and delete `includeSyntax` variable in related css files, but it do not work now, what's wrong with my method?

**Comment by i-a-n** [comment]
@Huang-Libo — I can't really say what's wrong without seeing the code. maybe if you publish it to a repo and link to it, I can help. but I'm not sure what's wrong just based on your description.

**Comment by Huang-Libo** [comment]
@i-a-n 
Hi, finally I solve this problem by add the code below to `head.html` and `footer.html`, and delete the code related with syntax.css in this theme.

```
<link rel="stylesheet" href="/css/tomorrow-night-bright.css">
<script src="/js/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

But another problem come: how can I Remove the border in code block? It seems have relationship with `bootstrap.min.css` or `bootstrap.css`.

![highlightjs](https://cloud.githubusercontent.com/assets/12227130/24762657/9683d130-1b21-11e7-9536-0cca763be63b.png)

**Comment by davidtmiller** [comment]
I'm going to close this for now. Jekyll has it's defaults, and if there are conflicts with Bootstrap rather than the theme itself then it's not relevant to the theme styles.
