### ISSUE TITLE
Headings in markdown

### ISSUE THREAD

**Issue by kulvait** [BlackrockDigital/startbootstrap-clean-blog-jekyll#119]
Hi,
i was trying to start blog with this template. I have created simple markdown page

```
---
layout: post
title: We are heading to Iceland
published: true
---
##Iceland, two people, one week and 1000EUR - preparation##

Text

###Dates
We are going **29th June and 5th July 2017**. 

###Keep it cheap
```

However the headings do not translate to the `<hx></hx>` tags but it stays as was written in markdown. It basically produces HTML code

```
<p>###Dates
We are going <strong>29th June and 5th July 2017</strong>. </p>
```

Strange think is that part of markup is translated and another part is not.
Do you have any tweak for this?
Thanks,
Vojtech.

**Comment by davidtmiller** [comment]
Make sure to put a space between the `#` and the content.
