### ISSUE TITLE
Some scss file missing for Bootstrap 4

### ISSUE THREAD

**Issue by user414** [BlackrockDigital/startbootstrap-clean-blog-jekyll#158]
First thanks for this theme and your other theme, we use an augmented merged version of the two. However, with 1014 fork we thought to check if someone hadn't done these update first before we spend some time on it. Otherwise we will probably update our fork with the pull request and boostrap 4.1.x, and other tweak we have until the main branch gets updated again.  

In Boostrap 4 media queries changed

> Media queries have also changed. Instead of repeating our media query declarations with the same value each time, we now have @include media-breakpoint-up/down/only. Now, instead of writing @media (min-width: @screen-sm-min) { ... }, you can write @include media-breakpoint-up(sm) { ... }.

but to use them those file are necessary

https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_breakpoints.scss
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_functions.scss

but is missing in the theme.

**Comment by user414** [comment]
We updated to bootstrap 4.1.1 and made some other changes as well as merge the outstanding pull request in our fork until the main branch gets updated. Feel free to merge from it or others to use it in the mean time.

**Comment by davidtmiller** [comment]
Should be fixed in the most recent update - I've pulled in 4.2.1
