### ISSUE TITLE
is this theme unmaintained? 

### ISSUE THREAD

**Issue by maxandersen** [BlackrockDigital/startbootstrap-clean-blog-jekyll#173]
first issue is the wrong theme name and while I was opening PR for it I saw it was already opened at https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll/pull/149 ...

are you looking for maintainers ?

**Comment by davidtmiller** [comment]
I just did a big bunch of updates, merged a ton of PR's, and pushed it all to a new version. I will be updating the theme more often from now on as well. Thank you for your assistance!
