### ISSUE TITLE
Page build warning 

### ISSUE THREAD

**Issue by huyennguyenqs** [BlackrockDigital/startbootstrap-clean-blog-jekyll#187]
I try to build in my local and it works perfectly with` jekyll-theme-clean-blog` theme.
But I got an issue when pushing my code into GitHub Pages:
```
You are attempting to use a Jekyll theme, "jekyll-theme-clean-blog", which is not supported by GitHub Pages.
```
Does anyone face this issue?

**Comment by huyennguyenqs** [comment]
Now after adding `gem "jekyll-remote-theme"`, Github Page can build my code.
But another issue happens, the paginate does not work :(

**Comment by NoobCam** [comment]
add the following line to your Gemfile

gem "jekyll-paginate"

    add the following lines your _config.yml

plugins:
  - jekyll-paginate  
paginate: 5
paginate_path: "/posts/page:num/"

**Comment by AlphaZeroError** [comment]
I am also get this build waring 
`The page build completed successfully, but returned the following warning for the `master` branch:
>
> You are attempting to use a Jekyll theme, "jekyll-theme-clean-blog", which is not supported by GitHub Pages.`

In the readme.md file I can't find variable lilke    `remote_theme: 'themename'  `
so I put like this `remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll`

But I still I got build same build warning message from github

**Comment by huyennguyenqs** [comment]
@NoobCam I also tried this, but it was not work.
@NoobCam @AlphaZeroError I resolved my problem by using Travis CI to build this source code.
Thank you guys! :))
