### ISSUE TITLE
  Liquid Exception: Liquid syntax error (line 8): Unknown tag 'when' in bundles/ruby/2.3.0/gems/liquid-4.0.3/lib/liquid/locales/en.yml

### ISSUE THREAD

**Issue by Tigerjieer** [BlackrockDigital/startbootstrap-clean-blog-jekyll#193]
When trying to build as per instructions, the following error is produced:

```
kona@arcticjieer:~/startbootstrap-clean-blog-jekyll$ bundle exec jekyll serve 
Configuration file: /home/kona/startbootstrap-clean-blog-jekyll/_config.yml
            Source: /home/kona/startbootstrap-clean-blog-jekyll
       Destination: /home/kona/startbootstrap-clean-blog-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 8): Unknown tag 'when' in bundles/ruby/2.3.0/gems/liquid-4.0.3/lib/liquid/locales/en.yml
jekyll 3.8.5 | Error:  Liquid syntax error (line 8): Unknown tag 'when'
kona@arcticjieer:~/startbootstrap-clean-blog-jekyll$ 
```
Preventing build

**Comment by Tigerjieer** [comment]
OK. Solved

**Comment by berthelemy** [comment]
Hi @ArcticKona I'm having the same issue. How did you fix it?

Thanks.

**Comment by berthelemy** [comment]
For reference, I discovered my problem was with a badly formed `exclude` command in _config.yml

**Comment by ranaalisaeed** [comment]
How was this solved? I'm facing the same issue and there are nothing in this issue log that's helpful.

**Comment by locness3** [comment]
@ArcticKona how did you fix this? saying "solved" is not helpful...

**Comment by tniezg** [comment]
The issue happens when you change `BUNDLE_PATH` to a path that's inside of a Jekyll project. In the case described it was changed to `bundles`. Jekyll will then try to parse `en.yml` as a Liquid template. To solve, you can add the path to `exclude` - https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll/issues/193#issuecomment-616184239 or change `bundles` to `.bundles`.
