### ISSUE TITLE
Your SCSS file `assets/main.scss` has an error on line 2: File to import not found or unreadable

### ISSUE THREAD

**Issue by fp-study** [BlackrockDigital/startbootstrap-clean-blog-jekyll#219]
Hi,
I have very excited by using your great theme! Thank you for opening theme-sources. 👍 

In this case, I have a problem that deploy fail.
Here is my "Page build failure" email contents.

```
The page build failed for the `master` branch with the following error:

Your SCSS file `assets/main.scss` has an error on line 2: File to import not found or unreadable: ../assets/vendor/startbootstrap-clean-blog/scss/clean-blog.scss. Load paths: _sass /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

At first, I saw that link in email.. but I cannot fix it.
On the otherhand, In my macOS Mojave, It has no problem. ( I can't understand...)

Would you help me to solve this problem?

Here is the [repository link](https://github.com/fp-study/fp-study.github.io).
Here is the [git-blog link](https://fp-study.github.io/). <- fail to deploy

Thank you for reading.

**Comment by fp-study** [comment]
I solve it!
Oh, it's my misstake that misunderstood about importing sass sources.
See this [StackOverFlow tip](https://stackoverflow.com/questions/51545661/jekyll-cannot-locate-an-included-file-in-main-scss-or-the-file-has-an-error?answertab=votes#tab-top)!

**Comment by fp-study** [comment]
Thank you for your sharing so wonderful theme! :)

**Comment by israeldav** [comment]
I'm having the same issue - getting this error on github pages, loads fine locally. 

`Your SCSS file assets/main.scss has an error on line 2: File to import not found or unreadable: ../assets/vendor/startbootstrap-clean-blog/scss/clean-blog.scss. Load paths: _sass /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass.`

I added 

`sass:
  sass_dir:   _sass
  style:      :compressed`

to config file, still wont build on github pages. 

Any help would be very much appreciated.

**Comment by christopherwhaas** [comment]
> I'm having the same issue - getting this error on github pages, loads fine locally.
> 
> `Your SCSS file assets/main.scss has an error on line 2: File to import not found or unreadable: ../assets/vendor/startbootstrap-clean-blog/scss/clean-blog.scss. Load paths: _sass /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass.`
> 
> I added
> 
> `sass: sass_dir: _sass style: :compressed`
> 
> to config file, still wont build on github pages.
> 
> Any help would be very much appreciated.



Try replacing the vendor with vendor/bundle in your .gitignore
