### ISSUE TITLE
Create New Posts_The Date Must Be 2020

### ISSUE THREAD

**Issue by Yifei-Yu-UTwente** [BlackrockDigital/startbootstrap-clean-blog-jekyll#282]
I found one weird issue in the post heads:

---
layout: post
title: "Welcome on Board!"
date: 2020-12-23 08:00:00 -0400
background: '/img/New_Homepage.jpg'
---

Where the date must be the year 2020, otherwise it does not comply. I wonder where can I modify it.

Thanks!

**Comment by Amina-Delali** [comment]
Hi. I had the same issue. I added the option: future: true in the _config.yml file.

**Comment by Yifei-Yu-UTwente** [comment]
Great! I noticed it as well. The time must not be in the future. Your solution is perfect. Thank you!
