### ISSUE TITLE
Jekyll serve error

### ISSUE THREAD

**Issue by banpie** [BlackrockDigital/startbootstrap-clean-blog-jekyll#52]
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.

**Comment by italoclone** [comment]
same problem!

**Comment by eluleci** [comment]
+1

**Comment by villasv** [comment]
The error message is pretty much self explanatory... just add the referred line to your config.yml
Like this:
```
### Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
paginate: 5
```

**Comment by davidtmiller** [comment]
Was that pull request merged @villasv?
