### ISSUE TITLE
PHP forms

### ISSUE THREAD

**Issue by Tazeg** [BlackrockDigital/startbootstrap-clean-blog-jekyll#53]
PHP mail form and JQuery are great but how to use my own forms ?
Because it seems that each form is tested and validated by JQuery.

For example, with this code in any page : 
<pre><code>&lt;form action=&quot;somescript.php&quot; method=&quot;POST&quot;&gt;</pre></code>

I got : 
<pre>Uncaught TypeError: Cannot read property 'indexOf' of undefinedclean-blog.min.js:7
$.jqBootstrapValidation.submitSuccessclean-blog.min.js:7
(anonymous function)jquery.min.js:3
n.event.dispatchjquery.min.js:3 
r.handle</pre>

So, how to disable JQuery for other forms than contact form ?
As the id="contactForm", why JQuery is not used only for this id ?

**Comment by davidtmiller** [comment]
This should have been fixed with a typo fix that I just made.
