### ISSUE TITLE
Tags/Categories Support

### ISSUE THREAD

**Issue by erayaydin** [BlackrockDigital/startbootstrap-clean-blog-jekyll#65]
I think, there should be a tags/categories support.

**Comment by ajkl** [comment]
+1 
 Is there a way to get feeds by category/tags ?

**Comment by nilsonsrjunior** [comment]
+1

**Comment by erayaydin** [comment]
I made a way for get feeds by category/tags : https://github.com/erayaydin/erayaydin.github.io

**Comment by nilsonsrjunior** [comment]
thank you very much @erayaydin !!!

**Comment by rouseguy** [comment]
Thanks @erayaydin

**Comment by davidtmiller** [comment]
I'll look into getting this added in a future version, thanks for the recommendation!
