### ISSUE TITLE
css not showing

### ISSUE THREAD

**Issue by samchan** [BlackrockDigital/startbootstrap-clean-blog-jekyll#7]
hello, 

thanks for setting up this theme. I am new to jekyll and github and pretty much coding in general!

I forked your theme, and tried to tweak it to setup a blog for myself, but I don't know why the CSS doesn't show up: http://d.pr/i/1kvV5/37q9O12B

What am i missing? 

i read somewhere that it's probably something wrong with the config.yml file, so I've screenshot that as well. http://d.pr/i/iuKP/2Ru0CL1j 

Thanks
Sam

**Comment by Faiz7412** [comment]
I am having the same problem. I just downloaded the zip and fired up index.html. CSS doesn't show.

![screenshot from 2015-03-21 00 46 35](https://cloud.githubusercontent.com/assets/8874731/6759195/5d9bb370-cf64-11e4-9482-97c6972d0484.png)
