### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by kamlekar** [BlackrockDigital/startbootstrap-clean-blog-jekyll#87]
Can someone please tell me where I need to change so that the contact form will work?

http://i.imgur.com/71XnrPd.png?1

I added my email address in `mail/contact_me.php` what else should I need to do?

    $to = 'mymailid@gmail.com'; // Add your email address inbetween the '' replacing yourname@yourdomain.com - This is where the form will send a message to.
    $email_subject = "Website Contact Form:  $name";
    $email_body = "You have received a new message from your website contact form.\n\n"."Here are the details:\n\nName: $name\n\nEmail: $email_address\n\nPhone: $phone\n\nMessage:\n$message";
    $headers = "From: mymailid@gmail.com\n"; // This is the email address the generated message will be from. We recommend using something like noreply@yourdomain.com.
    $headers .= "Reply-To: $email_address";
    mail($to,$email_subject,$email_body,$headers);
    return true;
    ?>

**Comment by ShikherVerma** [comment]
Github doesn't support php. You can try including a form using 3rd party plugins.

**Comment by kamlekar** [comment]
That is what I thought but was confused because this theme was using it. Thanks.

**Comment by ShikherVerma** [comment]
Try [this](https://formkeep.com/guides/how-to-make-a-contact-form-in-jekyll)
