### ISSUE TITLE
Beginner Help

### ISSUE THREAD

**Issue by JeffKaplan93** [BlackrockDigital/startbootstrap-clean-blog-jekyll#98]
Hello I just downloaded the template in a zip file to my desktop. Went to open in the index.html tab to start editing, When I preview the file, none of the styling, photos, are displaying at all. What step am I missing? I am novice, and haven't done this in a few months. Thank you

**Comment by JeffKaplan93** [comment]
![capture](https://cloud.githubusercontent.com/assets/17185014/17842166/fd218776-67ed-11e6-90cc-9fcb572863c4.JPG)

**Comment by davidtmiller** [comment]
If you want a pure HTML version check out the Clean Blog template (original non-Jekyll version) https://startbootstrap.com/template-overviews/clean-blog/

If you are wanting to use Jekyll then you will need to have Jekyll installed globally. Here is a code tutorial on setting up Jekyll http://code.tutsplus.com/articles/building-static-sites-with-jekyll--net-22211. Jekyll is a ruby gem and you need to have Ruby installed first. Once all of that is done, you can go back to the downloaded files and run the command `jekyll serve` in your terminal and it will show you the site!

**Comment by Geekince** [comment]
You missed the url setting at  _config.yml @JeffKaplan93
