### ISSUE TITLE
landing page option

### ISSUE THREAD

**Issue by lukemerrick** [BlackrockDigital/startbootstrap-clean-blog-jekyll#99]
For context, I'm currently upgrading a little landing page from BlackrockDigital's awesome Landing Page theme up to a full jekyll blog-enabled site with the Clean Blog theme. I love your guys's work and I really appreciate you sharing it open source so I can make my site pretty :+1: 

I'm new to Jekyll and not great with Bootstrap, so this may be a dumb thing to ask, but I would love to know how to keep the homepage very landing-page style with a large header graphic like your other theme while doing a site in this theme. I think adding a landing page template to the theme would be an awesome _feature extension_ for this project, but even just a little advice for changing the intro-header height without hackily overwritting stuff that should be handled by Bootstrap/Jekyll would be greatly appreciated. 

(and of course if this project turns out well, I'd be happy to make a pull request and add whatever landing-page template addition it ends up in, if that's a feature extension you guys think would benefit this project

Standard proportions for index page
![default example](https://cloud.githubusercontent.com/assets/8729935/18287813/962846ee-7446-11e6-9fff-b1a47a612271.png)

Desired proportions
![landing example](https://cloud.githubusercontent.com/assets/8729935/18287815/9975d47e-7446-11e6-8c4b-b771052e1821.png)

**Comment by davidtmiller** [comment]
You would need to add a lot of padding to the `header` component, or set it's height to `height: 100vh`.
